theme: jekyll-theme-midnight
permalink: /blog/:year/:month/:day/:title
port: 4000
auto: true
safe: true
server: true
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
